/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsinaOperacaoRouteImport } from './routes/usina-operacao'
import { Route as PortoOperacaoRouteImport } from './routes/porto-operacao'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FidelizacaoRouteImport } from './routes/fidelizacao'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as CcoRouteImport } from './routes/cco'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as IndexRouteImport } from './routes/index'

const UsinaOperacaoRoute = UsinaOperacaoRouteImport.update({
  id: '/usina-operacao',
  path: '/usina-operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortoOperacaoRoute = PortoOperacaoRouteImport.update({
  id: '/porto-operacao',
  path: '/porto-operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelizacaoRoute = FidelizacaoRouteImport.update({
  id: '/fidelizacao',
  path: '/fidelizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CcoRoute = CcoRouteImport.update({
  id: '/cco',
  path: '/cco',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/cco': typeof CcoRoute
  '/equipamentos': typeof EquipamentosRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/historico': typeof HistoricoRoute
  '/manutencao': typeof ManutencaoRoute
  '/operacao': typeof OperacaoRoute
  '/porto-operacao': typeof PortoOperacaoRoute
  '/usina-operacao': typeof UsinaOperacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/cco': typeof CcoRoute
  '/equipamentos': typeof EquipamentosRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/historico': typeof HistoricoRoute
  '/manutencao': typeof ManutencaoRoute
  '/operacao': typeof OperacaoRoute
  '/porto-operacao': typeof PortoOperacaoRoute
  '/usina-operacao': typeof UsinaOperacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/cco': typeof CcoRoute
  '/equipamentos': typeof EquipamentosRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/historico': typeof HistoricoRoute
  '/manutencao': typeof ManutencaoRoute
  '/operacao': typeof OperacaoRoute
  '/porto-operacao': typeof PortoOperacaoRoute
  '/usina-operacao': typeof UsinaOperacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/auth'
    | '/cco'
    | '/equipamentos'
    | '/fidelizacao'
    | '/historico'
    | '/manutencao'
    | '/operacao'
    | '/porto-operacao'
    | '/usina-operacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/auth'
    | '/cco'
    | '/equipamentos'
    | '/fidelizacao'
    | '/historico'
    | '/manutencao'
    | '/operacao'
    | '/porto-operacao'
    | '/usina-operacao'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/auth'
    | '/cco'
    | '/equipamentos'
    | '/fidelizacao'
    | '/historico'
    | '/manutencao'
    | '/operacao'
    | '/porto-operacao'
    | '/usina-operacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AuthRoute: typeof AuthRoute
  CcoRoute: typeof CcoRoute
  EquipamentosRoute: typeof EquipamentosRoute
  FidelizacaoRoute: typeof FidelizacaoRoute
  HistoricoRoute: typeof HistoricoRoute
  ManutencaoRoute: typeof ManutencaoRoute
  OperacaoRoute: typeof OperacaoRoute
  PortoOperacaoRoute: typeof PortoOperacaoRoute
  UsinaOperacaoRoute: typeof UsinaOperacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usina-operacao': {
      id: '/usina-operacao'
      path: '/usina-operacao'
      fullPath: '/usina-operacao'
      preLoaderRoute: typeof UsinaOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porto-operacao': {
      id: '/porto-operacao'
      path: '/porto-operacao'
      fullPath: '/porto-operacao'
      preLoaderRoute: typeof PortoOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelizacao': {
      id: '/fidelizacao'
      path: '/fidelizacao'
      fullPath: '/fidelizacao'
      preLoaderRoute: typeof FidelizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cco': {
      id: '/cco'
      path: '/cco'
      fullPath: '/cco'
      preLoaderRoute: typeof CcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AuthRoute: AuthRoute,
  CcoRoute: CcoRoute,
  EquipamentosRoute: EquipamentosRoute,
  FidelizacaoRoute: FidelizacaoRoute,
  HistoricoRoute: HistoricoRoute,
  ManutencaoRoute: ManutencaoRoute,
  OperacaoRoute: OperacaoRoute,
  PortoOperacaoRoute: PortoOperacaoRoute,
  UsinaOperacaoRoute: UsinaOperacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
