/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as IndexRouteImport } from './routes/index'

const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/equipamentos': typeof EquipamentosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/equipamentos': typeof EquipamentosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/equipamentos': typeof EquipamentosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/auth'
    | '/clientes'
    | '/equipamentos'
    | '/operacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acesso' | '/auth' | '/clientes' | '/equipamentos' | '/operacao'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/auth'
    | '/clientes'
    | '/equipamentos'
    | '/operacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  EquipamentosRoute: typeof EquipamentosRoute
  OperacaoRoute: typeof OperacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  EquipamentosRoute: EquipamentosRoute,
  OperacaoRoute: OperacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
