// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Endereços fixos para garantir funcionamento caso o ambiente falhe
const FALLBACK_URL = "https://zqzutizokctwpagnxanw.supabase.co";
const FALLBACK_KEY = "sb_publishable_ZqQhQ4v5-vHIwz_liZ4zfQ_7PXnWE6i";

function createSupabaseClient() {
  // Tenta ler do ambiente primeiro (Vite), senão usa o Plano B fixo
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message = `Erro: Chaves do Supabase não encontradas.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
